debug: true

spring:
  application:
    name: ged-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/ged_db
    username: ged_app_user
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ged-awb

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2:3b

server:
  port: 8080

tesseract:
  datapath: C:\Program Files\Tesseract-OCR\tessdata

ged:
  security:
    enabled: true
    allowed-origins: ${GED_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000,http://localhost:8080}
  storage:
    type: ${GED_STORAGE_TYPE:filesystem}
    base-path: ./storage-data
    minio:
      endpoint: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin123
      bucket: ged-documents

