spring:
  application:
    name: ged-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/ged_db
    username: postgres
    password: Alpha55@@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ged-awb

server:
  port: 8080