package com.awb.ged.infrastructure.persistence.entity.shared;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

/**
 * <h1>BaseEntity</h1>
 * <p>
 * Abstract JPA {@link MappedSuperclass} inherited by every entity in the GED-AWB system.
 * Centralizes the common lifecycle fields:
 * <ul>
 *   <li>{@code id}        — UUID primary key, generated via Hibernate's optimized UUID v4 generator.</li>
 *   <li>{@code createdAt} — Set once on first persist; never updated afterwards.</li>
 *   <li>{@code updatedAt} — Refreshed on every update via {@link PreUpdate}.</li>
 * </ul>
 * </p>
 *
 * <p><strong>Design Decision:</strong>
 * Using {@code @MappedSuperclass} (not {@code @Inheritance}) keeps the table structure flat —
 * each subclass maps to its own dedicated table, avoiding cross-table joins for basic fields.
 * </p>
 */
@Getter
@Setter
@MappedSuperclass
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Universally unique identifier — primary key for every entity.
     * Generated by Hibernate using a high-performance UUID v4 algorithm.
     * Immutable after creation.
     */
    @Id
    @UuidGenerator
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Timestamp of the record's first insertion into the database.
     * Set automatically by {@link #prePersist()} and never modified thereafter.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp of the record's most recent update.
     * Refreshed on every merge/update operation by {@link #preUpdate()}.
     */
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * JPA lifecycle callback executed before the entity is first persisted.
     * Initialises both {@code createdAt} and {@code updatedAt} to the current UTC instant.
     */
    @PrePersist
    protected void prePersist() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    /**
     * JPA lifecycle callback executed before every update operation.
     * Refreshes {@code updatedAt} to the current UTC instant.
     */
    @PreUpdate
    protected void preUpdate() {
        this.updatedAt = Instant.now();
    }
}
