package com.awb.ged.common.event;

import java.time.Instant;
import java.util.UUID;

/**
 * <h1>DomainEvent</h1>
 * <p>
 * Core contract representing a domain event generated by the business logic.
 * Domain events describe important occurrences in the life of the domain model (e.g. document creation, download, etc.).
 * </p>
 */
public interface DomainEvent {

    /**
     * Unique identifier for this event instance.
     *
     * @return the event {@link UUID}
     */
    UUID getEventId();

    /**
     * The timestamp of when the event occurred in UTC.
     *
     * @return the event occurrence {@link Instant}
     */
    Instant getOccurredAt();
}
