package com.awb.ged.infrastructure.persistence.entity.notification;

import com.awb.ged.infrastructure.persistence.entity.shared.BaseEntity;
import com.awb.ged.infrastructure.persistence.entity.user.UserJpaEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * <h1>NotificationJpaEntity</h1>
 * <p>
 * JPA entity representing a single notification delivered (or pending delivery) to a user.
 * </p>
 *
 * <p>
 * Notifications are generated by application events (e.g., "Document X was shared with you",
 * "Your checkout is expiring soon") and delivered via one or more channels.
 * Each channel delivery is represented as a separate row.
 * </p>
 *
 * <p><strong>Relationships:</strong></p>
 * <ul>
 *   <li>M:1 → {@link UserJpaEntity} — the notification recipient.</li>
 * </ul>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "notifications",
        indexes = {
                @Index(name = "idx_notif_user_status", columnList = "user_id, status, created_at DESC"),
                @Index(name = "idx_notif_unread",      columnList = "user_id")
        }
)
public class NotificationJpaEntity extends BaseEntity {

    /**
     * Delivery channel for this notification.
     */
    public enum Channel {
        IN_APP,
        EMAIL,
        PUSH
    }

    /**
     * Delivery lifecycle status of this notification.
     */
    public enum NotificationStatus {
        /** Queued, not yet sent */
        PENDING,
        /** Successfully delivered to the channel */
        SENT,
        /** Viewed/acknowledged by the user */
        READ,
        /** Delivery failed after retries */
        FAILED
    }

    /**
     * The user who should receive this notification.
     */
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "user_id",
            nullable = false,
            updatable = false,
            foreignKey = @ForeignKey(name = "fk_notifications_user")
    )
    private UserJpaEntity user;

    /**
     * Notification type code (e.g., {@code DOCUMENT_SHARED}, {@code CHECKOUT_EXPIRING}).
     * Used by the UI to render appropriate icons and routing.
     */
    @NotBlank
    @Size(max = 100)
    @Column(name = "type", nullable = false, length = 100)
    private String type;

    /**
     * Short title of the notification (shown as the notification header).
     */
    @NotBlank
    @Size(max = 255)
    @Column(name = "title", nullable = false, length = 255)
    private String title;

    /**
     * Full notification body text.
     */
    @NotBlank
    @Column(name = "body", nullable = false, columnDefinition = "TEXT")
    private String body;

    /**
     * Type of the related entity (e.g., {@code DOCUMENT}, {@code FOLDER}).
     * Used for deep-linking in the UI.
     */
    @Size(max = 50)
    @Column(name = "entity_type", length = 50)
    private String entityType;

    /**
     * UUID of the related entity for deep-linking.
     */
    @Column(name = "entity_id")
    private UUID entityId;

    /**
     * Delivery channel used for this notification.
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "channel", nullable = false, length = 30)
    @Builder.Default
    private Channel channel = Channel.IN_APP;

    /**
     * Current delivery status.
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private NotificationStatus status = NotificationStatus.PENDING;

    /**
     * Timestamp when the user read/acknowledged this notification.
     * {@code null} for unread notifications.
     */
    @Column(name = "read_at")
    private Instant readAt;

    /**
     * Timestamp when the notification was successfully dispatched to the channel.
     */
    @Column(name = "sent_at")
    private Instant sentAt;

    /**
     * Optional expiry timestamp — expired notifications are hidden from the UI.
     */
    @Column(name = "expires_at")
    private Instant expiresAt;
}
