package com.awb.ged.domain.document.model;

import lombok.Builder;
import lombok.Value;

/**
 * <h1>DocumentTag</h1>
 * <p>
 * Value Object representing a tag assigned to a document.
 * Supports indicators for AI automated tagging (with a confidence score).
 * </p>
 */
@Value
@Builder
public class DocumentTag {

    /** The tag label (e.g. "Facture", "Confidentiel") */
    String name;

    /** True if this tag was automatically suggested/generated by the AI pipeline */
    boolean generatedByIa;

    /** Confidence score of the AI prediction (value between 0.0 and 1.0; null if manually set) */
    Double confidence;
}
