package com.awb.ged.infrastructure.persistence.entity.ai;

import com.awb.ged.infrastructure.persistence.entity.shared.BaseEntity;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * <h1>AiChatMessageJpaEntity</h1>
 * <p>
 * JPA entity representing a single message turn within an {@link AiChatSessionJpaEntity}.
 * </p>
 *
 * <p>
 * Messages alternate between {@code USER} (questions) and {@code ASSISTANT} (AI answers).
 * {@code SYSTEM} messages are used for initial context injection (e.g., setting the
 * AI's persona or grounding instructions) and are not visible in the UI by default.
 * </p>
 *
 * <p><strong>Traceability / Citations:</strong>
 * For {@code ASSISTANT} messages, {@code retrievedChunks} stores a JSONB array
 * of chunk IDs and their similarity scores from the vector store query.
 * {@code sourceDocuments} stores the version UUIDs of all documents that contributed
 * context chunks to the answer — enabling UI citations like "Based on: Document X v2".
 * </p>
 *
 * <p><strong>Relationships:</strong></p>
 * <ul>
 *   <li>M:1 → {@link AiChatSessionJpaEntity} — the parent session.</li>
 * </ul>
 *
 * <p><strong>Design Decision — {@code @NotNull} on {@code session}:</strong>
 * Messages cannot exist without a session. The {@code CascadeType.ALL + orphanRemoval}
 * on the session side ensures messages are deleted when the session is closed/purged.
 * </p>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "ai_chat_messages",
        indexes = {
                @Index(name = "idx_chat_messages_session_id", columnList = "session_id, created_at ASC")
        }
)
public class AiChatMessageJpaEntity extends BaseEntity {

    /**
     * Role of the message author in the conversation.
     */
    public enum Role {
        /** Message sent by the human user */
        USER,
        /** Message generated by the AI assistant */
        ASSISTANT,
        /** System-injected context/instruction (not shown in UI) */
        SYSTEM
    }

    /**
     * Simple user feedback signal on an AI response.
     */
    public enum Feedback {
        THUMBS_UP,
        THUMBS_DOWN
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Session reference
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * The conversation session this message belongs to.
     */
    @NotNull
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "session_id",
            nullable = false,
            updatable = false,
            foreignKey = @ForeignKey(name = "fk_chat_messages_session")
    )
    private AiChatSessionJpaEntity session;

    // ─────────────────────────────────────────────────────────────────────────
    //  Message content
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Role of the author of this message.
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    private Role role;

    /**
     * Full text content of the message.
     * For {@code ASSISTANT} messages this is the AI-generated answer.
     * For {@code USER} messages this is the user's question.
     */
    @NotBlank
    @Column(name = "content", nullable = false, columnDefinition = "TEXT")
    private String content;

    // ─────────────────────────────────────────────────────────────────────────
    //  RAG retrieval metadata (populated for ASSISTANT messages only)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * JSONB array of vector-store chunks retrieved to generate this answer.
     * Each element includes the chunk ID, its similarity score, and source version ID.
     * Example:
     * <pre>{@code
     * [
     *   {"embeddingId": "uuid", "score": 0.92, "versionId": "uuid"},
     *   {"embeddingId": "uuid", "score": 0.87, "versionId": "uuid"}
     * ]
     * }</pre>
     * {@code null} for {@code USER} and {@code SYSTEM} messages.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "retrieved_chunks", columnDefinition = "jsonb")
    private Object retrievedChunks;

    /**
     * JSONB array of document version UUIDs that contributed to this answer.
     * Displayed in the UI as "Sources" or "Citations".
     * Example: {@code ["uuid-of-version-1", "uuid-of-version-2"]}.
     * {@code null} for {@code USER} and {@code SYSTEM} messages.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "source_documents", columnDefinition = "jsonb")
    private Object sourceDocuments;

    // ─────────────────────────────────────────────────────────────────────────
    //  Performance & observability
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Total number of tokens consumed for this message (prompt + completion).
     * Used for cost tracking and model context window management.
     */
    @Column(name = "token_count")
    private Integer tokenCount;

    /**
     * End-to-end latency of the AI response generation in milliseconds.
     * Populated for {@code ASSISTANT} messages only.
     */
    @Column(name = "latency_ms")
    private Integer latencyMs;

    // ─────────────────────────────────────────────────────────────────────────
    //  User feedback
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Optional thumbs-up / thumbs-down feedback provided by the user
     * on an {@code ASSISTANT} message.
     * {@code null} means no feedback has been given.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "feedback", length = 20)
    private Feedback feedback;
}
